spring:
  application:
    name: gateway
  autoconfigure:
    exclude:
      - org.springframework.cloud.autoconfigure.LifecycleMvcEndpointAutoConfiguration
      - org.springframework.cloud.autoconfigure.RefreshAutoConfiguration
      - org.springframework.cloud.autoconfigure.RefreshEndpointAutoConfiguration
      - org.springframework.cloud.client.discovery.simple.SimpleDiscoveryClientAutoConfiguration
      - org.springframework.cloud.client.discovery.composite.CompositeDiscoveryClientAutoConfiguration
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://order-service:8081
          predicates:
            - Path=/orders/**
        - id: inventory-service
          uri: http://inventory-service:8082
          predicates:
            - Path=/inventory/**
        - id: notification-service
          uri: http://notification-service:8083
          predicates:
            - Path=/notifications/**

server:
  port: 8080
